import { useCallback, useEffect, useMemo, useState } from "react";
import { Megaphone } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { clubService } from "../../services/clubService";
import { announcementService } from "../../services/announcementService";
import GlassSurface from "../../components/GlassSurface/GlassSurface";
import PageState from "../../components/ui/PageState";
import "../../components/ui/PageState.css";
import "../clubs/Clubs.css";
import "./Announcements.css";

function Announcements() { const { user } = useAuth(); const [items, setItems] = useState([]); const [state, setState] = useState("loading"); const [error, setError] = useState(""); const load = useCallback(async () => { setState("loading"); try { const [clubs, memberships] = await Promise.all([clubService.getClubs(), user.role === "student" ? clubService.getMemberships(`?student=${encodeURIComponent(user.userId)}`) : Promise.resolve([])]); const ids = user.role === "student" ? memberships.map((item) => item.club_id) : clubs.filter((club) => club.faculty_id === user.userId).map((club) => club.club_id); const lists = await Promise.all(ids.map((clubId) => announcementService.getAnnouncements(`?club=${encodeURIComponent(clubId)}`))); setItems(lists.flat()); setState("ready"); } catch (loadError) { setError(loadError.message); setState("error"); } }, [user.role, user.userId]); useEffect(() => { load(); }, [load]); const ordered = useMemo(() => [...items].sort((a,b) => new Date(b.created_at) - new Date(a.created_at)), [items]); if (state === "loading") return <PageState title="Loading announcements" message="Fetching updates from your clubs…" />; if (state === "error") return <PageState type="error" title="Could not load announcements" message={error} onRetry={load} />; return <section className="feature-page"><div className="page-heading"><div><p>WORKSPACE / ANNOUNCEMENTS</p><h1>Announcements<span>.</span></h1><span>Latest notices from your clubs and events.</span></div></div>{!ordered.length ? <PageState title="No announcements yet" message="There are no announcements associated with your current clubs." /> : <div className="announcement-cards">{ordered.map((announcement) => <GlassSurface key={announcement.announcement_id} width="100%" borderRadius={18} backgroundOpacity={0.08} blur={12}><article className="announcement-card"><div className="announcement-icon"><Megaphone size={19} /></div><div><small>{announcement.club_name || announcement.club_id}{announcement.event_name ? ` · ${announcement.event_name}` : ""}</small><h2>{announcement.title}</h2><p>{announcement.content}</p><footer>Posted by {announcement.created_by_name || announcement.created_by_id} · {announcement.created_at ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(announcement.created_at)) : "Date unavailable"}</footer></div></article></GlassSurface>)}</div>}<p className="read-only-note">Announcement creation and editing are not exposed because the backend currently provides a read-only endpoint.</p></section>; }
export default Announcements;
