import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Circle, Flag } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { clubService } from "../../services/clubService";
import { taskService } from "../../services/taskService";
import GlassSurface from "../../components/GlassSurface/GlassSurface";
import PageState from "../../components/ui/PageState";
import "../../components/ui/PageState.css";
import "../clubs/Clubs.css";
import "./Tasks.css";

const date = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "No deadline";
function Tasks() { const { user } = useAuth(); const [tasks, setTasks] = useState([]); const [state, setState] = useState("loading"); const [error, setError] = useState(""); const load = useCallback(async () => { setState("loading"); try { if (user.role === "student") { setTasks(await taskService.getTasks(`?student=${encodeURIComponent(user.userId)}`)); } else { const clubs = await clubService.getClubs(); const owned = clubs.filter((club) => club.faculty_id === user.userId); const lists = await Promise.all(owned.map((club) => taskService.getTasks(`?club=${encodeURIComponent(club.club_id)}`))); setTasks(lists.flat()); } setState("ready"); } catch (loadError) { setError(loadError.message); setState("error"); } }, [user.role, user.userId]); useEffect(() => { load(); }, [load]); const ordered = useMemo(() => [...tasks].sort((a,b) => new Date(a.deadline) - new Date(b.deadline)), [tasks]); if (state === "loading") return <PageState title="Loading tasks" message="Fetching tasks relevant to your account…" />; if (state === "error") return <PageState type="error" title="Could not load tasks" message={error} onRetry={load} />; return <section className="feature-page"><div className="page-heading"><div><p>WORKSPACE / TASKS</p><h1>{user.role === "student" ? "My tasks" : "Club tasks"}<span>.</span></h1><span>Tasks returned by the ClubHub backend for your account.</span></div></div>{!ordered.length ? <PageState title="No tasks to show" message="There are no task records assigned to this account." /> : <div className="task-cards">{ordered.map((task) => <GlassSurface key={task.task_id} width="100%" borderRadius={17} backgroundOpacity={0.08} blur={12}><article className="task-card"><div className={`task-status ${task.status?.toLowerCase().includes("complete") ? "done" : ""}`}>{task.status?.toLowerCase().includes("complete") ? <CheckCircle2 size={20} /> : <Circle size={20} />}</div><div className="task-main"><div className="task-topline"><small>{task.club_name || task.club_id}</small><span className={`priority ${task.priority?.toLowerCase()}`}>{task.priority || "Normal"}</span></div><h2>{task.title}</h2><p>{task.description || "No task description provided."}</p><footer><span><Flag size={14} /> Due {date(task.deadline)}</span><span>{task.department_name || task.event_name || "General task"}</span></footer></div></article></GlassSurface>)}</div>}<p className="read-only-note">Task updates, assignments, and submissions are unavailable because this backend currently exposes read-only task endpoints.</p></section>; }
export default Tasks;
