import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Building2, ChevronRight, Users } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { clubService } from "../../services/clubService";
import GlassSurface from "../../components/GlassSurface/GlassSurface";
import PageState from "../../components/ui/PageState";
import "../../components/ui/PageState.css";
import "./Clubs.css";

function Clubs() {
    const { user } = useAuth();
    const [clubs, setClubs] = useState([]); const [memberships, setMemberships] = useState([]); const [selected, setSelected] = useState(null); const [members, setMembers] = useState([]); const [state, setState] = useState("loading"); const [error, setError] = useState("");
    const load = useCallback(async () => { setState("loading"); try { const [allClubs, membershipData] = await Promise.all([clubService.getClubs(), user.role === "student" ? clubService.getMemberships(`?student=${encodeURIComponent(user.userId)}`) : Promise.resolve([])]); const visible = user.role === "student" ? allClubs.filter((club) => membershipData.some((membership) => membership.club_id === club.club_id)) : allClubs.filter((club) => club.faculty_id === user.userId); setClubs(visible); setMemberships(membershipData); setState("ready"); } catch (loadError) { setError(loadError.message); setState("error"); } }, [user.role, user.userId]);
    useEffect(() => { load(); }, [load]);
    const selectedMembership = useMemo(() => memberships.find((membership) => membership.club_id === selected?.club_id), [memberships, selected]);
    const openClub = async (club) => { setSelected(club); setMembers([]); try { setMembers(await clubService.getMemberships(`?club=${encodeURIComponent(club.club_id)}`)); } catch (memberError) { setError(memberError.message); } };
    if (state === "loading") return <PageState title="Loading your clubs" message="Fetching your club memberships…" />;
    if (state === "error") return <PageState type="error" title="Could not load clubs" message={error} onRetry={load} />;
    if (selected) return <section className="feature-page"><button className="back-button" onClick={() => setSelected(null)}><ArrowLeft size={16} /> All clubs</button><div className="page-heading"><div><p>CLUB DIRECTORY</p><h1>{selected.club_name}</h1><span>{selected.category} · {selected.status}</span></div></div><div className="club-detail-grid"><GlassSurface width="100%" borderRadius={20} backgroundOpacity={0.08} blur={12}><article className="detail-card"><h2>About this club</h2><p>{selected.description || "No description has been added yet."}</p><dl><div><dt>Faculty coordinator</dt><dd>{selected.faculty_name || "Not listed"}</dd></div><div><dt>Your role</dt><dd>{selectedMembership?.role_name || (user.role === "faculty" ? "Faculty coordinator" : "Member")}</dd></div></dl></article></GlassSurface><GlassSurface width="100%" borderRadius={20} backgroundOpacity={0.08} blur={12}><article className="detail-card"><h2>Members <span>{members.length}</span></h2>{members.length ? <ul className="member-mini-list">{members.map((member) => <li key={member.student_id}><span>{member.student_name?.charAt(0) || "M"}</span><div><strong>{member.student_name || member.student_id}</strong><small>{member.role_name || "Member"}</small></div></li>)}</ul> : <p>No members found for this club.</p>}</article></GlassSurface></div></section>;
    return <section className="feature-page"><div className="page-heading"><div><p>WORKSPACE / CLUBS</p><h1>My clubs<span>.</span></h1><span>Clubs connected to your ClubHub account.</span></div></div>{clubs.length === 0 ? <PageState type="empty" title="No clubs to show" message="Your account does not currently have any club memberships or coordinator assignments." /> : <div className="club-grid">{clubs.map((club) => <GlassSurface key={club.club_id} width="100%" borderRadius={20} backgroundOpacity={0.08} blur={12}><button className="club-card" onClick={() => openClub(club)}><div className="club-card-icon"><Building2 size={21} /></div><small>{club.category}</small><h2>{club.club_name}</h2><p>{club.description || "Explore this club and its membership."}</p><footer><span><Users size={15} /> {memberships.filter((membership) => membership.club_id === club.club_id).length || "View"} members</span><ChevronRight size={18} /></footer></button></GlassSurface>)}</div>}</section>;
}
export default Clubs;
